CookBook

--------第一章--------
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

w=[1,1,1,2,2,3]

from collections import Counter

wc=Counter(w)

a=wc.most_common(2)

a
Out[5]: [(1, 3), (2, 2)]

wc.update()

wc
Out[7]: Counter({1: 3, 2: 2, 3: 1})

class User:
    def_init_(self,user_id)
    self.user_id=user_id
    def  _repr_(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-8-c8b9ca250f7c>", line 1, in <module>
    class User:

  File "<ipython-input-8-c8b9ca250f7c>", line 2, in User
    def_init_(self,user_id)

NameError: name 'def_init_' is not defined




class User:
    def__init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        
Traceback (most recent call last):

  File "<ipython-input-9-7cd6e6810379>", line 1, in <module>
    class User:

  File "<ipython-input-9-7cd6e6810379>", line 2, in User
    def__init__(self,user_id)

NameError: name 'def__init__' is not defined




class User:
    def __init__(self,user_id)
    self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
  File "<ipython-input-10-894c834986f6>", line 2
    def __init__(self,user_id)
                              ^
SyntaxError: invalid syntax




class User:
    def __init__(self,user_id):
        self.user_id=user_id
    def  __repr__(self):
        return 'User({})'.format(self.user_id)
        

users=[User(23),user(3),User(99)]
Traceback (most recent call last):

  File "<ipython-input-12-7645bd143d45>", line 1, in <module>
    users=[User(23),user(3),User(99)]

NameError: name 'user' is not defined




users=[User(23),User(3),User(99)]

sorted(users,key=lambda u: u,user_id)
  File "<ipython-input-14-5c8fe9ed8fad>", line 1
    sorted(users,key=lambda u: u,user_id)
                                ^
SyntaxError: positional argument follows keyword argument




sorted(users,key=lambda u: u.user_id)
Out[15]: [User(3), User(23), User(99)]

from operator import attrgetter

sorted(users,key=attrgetter('user_id'))
Out[17]: [User(3), User(23), User(99)]

min(user,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-18-9a9e70eb7113>", line 1, in <module>
    min(user,key=attrgetter('user_name'))

NameError: name 'user' is not defined




min(usesr,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-19-f83322a96f15>", line 1, in <module>
    min(usesr,key=attrgetter('user_name'))

NameError: name 'usesr' is not defined




min(users,key=attrgetter('user_name'))
Traceback (most recent call last):

  File "<ipython-input-20-2de890a3f6ee>", line 1, in <module>
    min(users,key=attrgetter('user_name'))

AttributeError: 'User' object has no attribute 'user_name'




min(users,key=attrgetter('user_id'))
Out[21]: User(3)

man(users,key=attrgetter('user_id'))
Traceback (most recent call last):

  File "<ipython-input-22-95390105d206>", line 1, in <module>
    man(users,key=attrgetter('user_id'))

NameError: name 'man' is not defined




max(users,key=attrgetter('user_id'))
Out[23]: User(99)

rows=[
{'address':'5412 CLARK','date':'07/01/2012'},
{'address':'1412 CLARK','date':'07/01/2016'},
{'address':'2412 CLARK','date':'07/01/2019'}]

from operator import itemgetter

from itertools import groupby

row.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-27-ffe702f8eb0d>", line 1, in <module>
    row.sort(key=itemgetter('data'))

NameError: name 'row' is not defined




rows.sort(key=itemgetter('data'))
Traceback (most recent call last):

  File "<ipython-input-28-ded3f87680e0>", line 1, in <module>
    rows.sort(key=itemgetter('data'))

KeyError: 'data'




rows.sort(key=itemgetter('date'))

rows
Out[30]: 
[{'address': '5412 CLARK', 'date': '07/01/2012'},
 {'address': '1412 CLARK', 'date': '07/01/2016'},
 {'address': '2412 CLARK', 'date': '07/01/2019'}]

from date,items in groupby(rows,key=itemgetter('date')):
    print(date)
  File "<ipython-input-31-ded8b3e4eaf1>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)/
  File "<ipython-input-32-4dd3b05cfc92>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date'))
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-33-e9dafca7d617>", line 1
    from date,items in groupby(rows,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows ,key=itemgetter('date'))
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-34-d2edb808cae3>", line 1
    from date,items in groupby(rows ,key=itemgetter('date'))
             ^
SyntaxError: invalid syntax




runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "d:\Users\16476\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-35-a188ba00e4e9>", line 1, in <module>
    runfile('C:/Users/16476/untitled0.py', wdir='C:/Users/16476')

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "d:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled0.py", line 9
    print('  ',i)
                 
^
SyntaxError: EOF while scanning triple-quoted string literal




from date,items in groupby(rows ,key=itemgetter('date')):
    print(date)\ 
    for i in items:
        print('  ',i)
  File "<ipython-input-36-665a94da095b>", line 1
    from date,items in groupby(rows ,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




from date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-37-98ac19b98562>", line 1
    from date,items in groupby(rows,key=itemgetter('date')):
             ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)\
    for i in items:
        print('  ',i)
  File "<ipython-input-38-043ef2cbeca1>", line 3
    for i in items:
      ^
SyntaxError: invalid syntax




for date,items in groupby(rows,key=itemgetter('date')):
    print(date)
    for i in items:
        print('  ',i) 
        
07/01/2012
   {'address': '5412 CLARK', 'date': '07/01/2012'}
07/01/2016
   {'address': '1412 CLARK', 'date': '07/01/2016'}
07/01/2019
   {'address': '2412 CLARK', 'date': '07/01/2019'}
 from collections import namedtuple

s=namedtuple('S',['A''B'])

s=namedtuple('Sb',['A''B'])

s
Out[49]: __main__.Sb

sb
Traceback (most recent call last):

  File "<ipython-input-50-2e29fd6b6233>", line 1, in <module>
    sb

NameError: name 'sb' is not defined




Sb
Traceback (most recent call last):

  File "<ipython-input-51-09d66f3f1d43>", line 1, in <module>
    Sb

NameError: name 'Sb' is not defined




sub=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-52-b9ab37554950>", line 1, in <module>
    sub=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




s=namedtuple('s',['A''B'])

sc=s('c','d')
Traceback (most recent call last):

  File "<ipython-input-54-c37c11b9961a>", line 1, in <module>
    sc=s('c','d')

TypeError: __new__() takes 2 positional arguments but 3 were given




sc=('c')

sc
Out[56]: 'c'

sc=s('s')

sc
Out[58]: s(AB='s')

import numpy as np

np.random.randint(10,size=10)
Out[60]: array([7, 7, 3, 7, 3, 5, 0, 2, 4, 4])

a=np.random.randint(10,size=10)

a
Out[62]: array([9, 2, 9, 1, 3, 8, 6, 6, 7, 0])

s=sum(a)

s
Out[64]: 51

s=sum(x**x for x in a)

s
Out[66]: 792535082

   



import os

file=os.listdir('dirname')
Traceback (most recent call last):

  File "<ipython-input-68-ffd0d57c2f8d>", line 1, in <module>
    file=os.listdir('dirname')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'dirname'




file=os.listdir('%dirs')
Traceback (most recent call last):

  File "<ipython-input-69-73428e3e7cb8>", line 1, in <module>
    file=os.listdir('%dirs')

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '%dirs'




file=os.listdir()

file
Out[71]: 
['.anaconda',
 '.android',
 '.AndroidStudio3.2',
 '.bash_history',
 '.BigNox',
 '.conda',
 '.condarc',
 '.config',
 '.emulator_console_auth_token',
 '.gitconfig',
 '.gradle',
 '.idlerc',
 '.ipython',
 '.LdVirtualBox',
 '.matplotlib',
 '.spyder-py3',
 '.ssh',
 '.VirtualBox',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'd4ac4633ebd6440fa397b84f1bc94a3c.7z',
 'Favorites',
 'Foxit Reader SDK ActiveX.ini',
 'Hello.java',
 'inittk.ini',
 'inst.ini',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'Nox_share',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TM.blf',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{acf20663-1ba4-11e8-83d4-f894c2bd03de}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'ntuser.pol',
 'nuuid.ini',
 'Pictures',
 'pip',
 'PrintHood',
 'python123demo',
 'Recent',
 'Saved Games',
 'scikit_learn_data',
 'Searches',
 'SendTo',
 'skb.kc',
 'source',
 'Templates',
 'UnblockNeteaseMusic-master',
 'untitled0.py',
 'useruid.ini',
 'Videos',
 'VirtualBox VMs',
 'vmlogs',
 '「开始」菜单']

s=('acme'50,,123.45)
  File "<ipython-input-72-d18d344791bb>", line 1
    s=('acme'50,,123.45)
              ^
SyntaxError: invalid syntax




s=('acme',50,123.45)

print(','.join(str(x) for x in s))
acme,50,123.45

a={'x':1'y':2}
  File "<ipython-input-75-f88a488f0b98>", line 1
    a={'x':1'y':2}
              ^
SyntaxError: invalid syntax




a={'x':1,'y':2}

a
Out[77]: {'x': 1, 'y': 2}

b={'y':3,'z':4}

from collections import ChainMap

c=ChainMap(a,b)

c
Out[81]: ChainMap({'x': 1, 'y': 2}, {'y': 3, 'z': 4})

--------第二章--------

re.split(r'[;,\s]\s*',line)
Out[85]: ['kaja', 'kaefj', 'aekl', 'eaklf', 'fff']

filename='scji.py'

filename.endswith('txt')
Out[87]: False

s='{name} is {f}'

s.format(name='fish',f='me')
Out[276]: 'fish is me'

name='i'

f='fish'

s.format_map(vars())
Out[279]: 'i is fish'

class Info:
    def __init__(self,name,f):
        self.name=name
        self.f=f
        

a=info(10,4)
Traceback (most recent call last):

  File "<ipython-input-281-a0dd896fa1fa>", line 1, in <module>
    a=info(10,4)

NameError: name 'info' is not defined




a=Info(10,4)

a
Out[283]: <__main__.Info at 0x2504b8ef248>

s.format_map(vars(a))
Out[284]: '10 is 4'

s.format(name=0)
Traceback (most recent call last):

  File "<ipython-input-285-cffadfed4ad8>", line 1, in <module>
    s.format(name=0)

KeyError: 'f'

textwrap.fill(s,77)
Out[315]: '我是一段很长很长很长的长字符，以至于我得转义换行，接着再换行'

textwrap.fill(s,3)
Out[316]: '我是一\n段很长\n很长很\n长的长\n字符，\n以至于\n我得转\n义换行\n，接着\n再换行'

print(textwrap.fill(s,3))
我是一
段很长
很长很
长的长
字符，
以至于
我得转
义换行
，接着
再换行

print(textwrap.fill(s,10,initial_indent=' '))
 我是一段很长很长很
长的长字符，以至于我
得转义换行，接着再换
行

print(textwrap.fill(s,10))
我是一段很长很长很长
的长字符，以至于我得
转义换行，接着再换行

print(textwrap.fill(s,10,subsequent_indent=' '))
我是一段很长很长很长
 的长字符，以至于我
 得转义换行，接着再
 换行

import os

os.get_terminal_size().columns
Traceback (most recent call last):

  File "<ipython-input-322-863e08fd3df5>", line 1, in <module>
    os.get_terminal_size().columns

OSError: [WinError 6] 句柄无效。




os.get_terminal_size().columns
Traceback (most recent call last):

  File "<ipython-input-323-863e08fd3df5>", line 1, in <module>
    os.get_terminal_size().columns

OSError: [WinError 6] 句柄无效。




s='<html>haha</html>'

import html

html.escape(s)
Out[326]: '&lt;html&gt;haha&lt;/html&gt;'

s.encode('ascii')
Out[327]: b'<html>haha</html>'

text='foo
  File "<ipython-input-328-6550bbabdd60>", line 1
    text='foo
             ^
SyntaxError: EOL while scanning string literal




text='foo=23+42*10'

import re

NAME=r'?P<NAME>[[a-zA-Z_0-9]*)'

NAME=r'?P<NAME>[[a-zA-Z_][a-zA-Z_0-9]*)'

NUM=r'(?P<NUM>\d+)'

PLUS=r'(?P<PLUS>\d+)'

PLUS=r'(?P<PLUS>\+)'

TIMES=r'(？P<TIMES>\*)'

EQ=r'(?P<EQ>=)'

WS=r'(?P<WS>\s+)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-339-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




NAME=r'?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-341-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




TIMES=r'(?P<TIMES>\*)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))
Traceback (most recent call last):

  File "<ipython-input-343-7165229117c2>", line 1, in <module>
    master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




'|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])
Out[344]: '?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)|(?P<NUM>\\d+)|(?P<PLUS>\\+)|(?P<TIMES>\\*)|(?P<EQ>=)|(?P<WS>\\s+)'

rec='|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])

re=re.compile(rec)
Traceback (most recent call last):

  File "<ipython-input-346-dbe4bd3b4a4d>", line 1, in <module>
    re=re.compile(rec)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))

  File "d:\Users\16476\Anaconda3\lib\sre_parse.py", line 651, in _parse
    source.tell() - here + len(this))

error: nothing to repeat




NAME = r'(?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)'
NUM = r'(?P<NUM>\d+)'
PLUS = r'(?P<PLUS>\+)'
TIMES = r'(?P<TIMES>\*)'
EQ = r'(?P<EQ>=)'
WS = r'(?P<WS>\s+)'

master_pat=re.compile('|'.join([NAME,NUM,PLUS,TIMES,EQ,WS]))

rec='|'.join([NAME,NUM,PLUS,TIMES,EQ,WS])

rec
Out[350]: '(?P<NAME>[a-zA-Z_][a-zA-Z_0-9]*)|(?P<NUM>\\d+)|(?P<PLUS>\\+)|(?P<TIMES>\\*)|(?P<EQ>=)|(?P<WS>\\s+)'

scanner=master_pat('foo= 42')
Traceback (most recent call last):

  File "<ipython-input-351-8c5fb04b62db>", line 1, in <module>
    scanner=master_pat('foo= 42')

TypeError: 're.Pattern' object is not callable




scanner=master_pat.scanner('foo= 42')

scanner.match
Out[353]: <function SRE_Scanner.match()>

scanner.match()
Out[354]: <re.Match object; span=(0, 3), match='foo'>

_.lastgroup,_.group()
Out[355]: ('NAME', 'foo')

_.lastgroup,_.group()
Traceback (most recent call last):

  File "<ipython-input-356-41a1219e790e>", line 1, in <module>
    _.lastgroup,_.group()

AttributeError: 'tuple' object has no attribute 'lastgroup'




scanner.match()
Out[357]: <re.Match object; span=(3, 4), match='='>

_.lastgroup,_.group()
Out[358]: ('EQ', '=')

_.lastgroup,_.group()
Traceback (most recent call last):

  File "<ipython-input-359-41a1219e790e>", line 1, in <module>
    _.lastgroup,_.group()

AttributeError: 'tuple' object has no attribute 'lastgroup'




scanner.match()
Out[360]: <re.Match object; span=(4, 5), match=' '>

_.lastgroup,_.group()
Out[361]: ('WS', ' ')

scanner.match()
Out[362]: <re.Match object; span=(5, 7), match='42'>

_.lastgroup,_.group()
Out[363]: ('NUM', '42')

scanner.match()

from collections import  namedtuple

Token=namedtuple('Token',['type','value'])

def generate_tokens(pat,text):
    scanner=pat.scanner(text)
    for m in iter(scanner.match,None):
        yield Token(m.lastgroup,m.group())
        

for tok in generate_tokens(master_pat,'foo= 33+22'):
    print(tok)
    
Token(type='NAME', value='foo')
Token(type='EQ', value='=')
Token(type='WS', value=' ')
Token(type='NUM', value='33')
Token(type='PLUS', value='+')
Token(type='NUM', value='22')

n [89]: 

int('11111111',8)
Out[89]: 2396745

int('11111111',3)
Out[90]: 3280

data=b'\x00\x124v\x00'

len(data)
Out[92]: 5

a=complex(2,4)

b=3-5j

a
Out[95]: (2+4j)

b
Out[96]: (3-5j)

a.real
Out[97]: 2.0

a.imag
Out[98]: 4.0

a.conjugate
Out[99]: <function complex.conjugate>

a.conjugate()
Out[100]: (2-4j)

abs(a)
Out[101]: 4.47213595499958

import cmath

cmath.cos(0)
Out[103]: (1-0j)

cmath.cos(a)
Out[104]: (-11.36423470640106-24.814651485634187j)

cmath.sqrt(-1)
Out[105]: 1j

 a=float('inf')

a
Out[107]: inf

a=float('nan')

a
Out[109]: nan

math.isnan(a)
Out[110]: True

from fractions import Fraction

a=Fraction(5,4)

a
Out[113]: Fraction(5, 4)

b=Fraction(3,2)

print(a+b)
11/4

print(a)
5/4

c=a*b

c
Out[118]: Fraction(15, 8)

c.numerator
Out[119]: 15

c.denominator
Out[120]: 8

float(c)
Out[121]: 1.875

print(c.limit_denominator(8))
15/8

print(c.limit_denominator(7))
13/7

print(c.limit_denominator(2))
2

import numpy as np

x=[1,2,3,4]

y=[5,6,7,8]

x*2
Out[128]: [1, 2, 3, 4, 1, 2, 3, 4]

x+10
Traceback (most recent call last):

  File "<ipython-input-129-e0cbb565319e>", line 1, in <module>
    x+10

TypeError: can only concatenate list (not "int") to list




x+y
Out[130]: [1, 2, 3, 4, 5, 6, 7, 8]

ax=np.arrange(10)
Traceback (most recent call last):

  File "<ipython-input-131-d91542cd4b53>", line 1, in <module>
    ax=np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'




ax=np.array(np.arange(10))

ax
Out[133]: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ax*2
Out[134]: array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

ax+10
Out[135]: array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

ax*ax
Out[136]: array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

np.sqrt(ax)
Out[137]: 
array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

np.cos(ax)
Out[138]: 
array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

grid=np.zeros(shape=(10000,10000),dtype=float)

grid
Out[140]: 
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

grid+=10

grid+=10

grid
Out[143]: 
array([[20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       ...,
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.]])

a=np.array(np.arange(1,13)).reshape(3,4)

a
Out[145]: 
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

a[1:3,1:3]
Out[146]: 
array([[ 6,  7],
       [10, 11]])

a[1:3,1:3]+=10

a[1:3,1:3]
Out[148]: 
array([[16, 17],
       [20, 21]])

a
Out[149]: 
array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

a[:,:]
Out[150]: 
array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

a+[1,1,1,1]
Out[151]: 
array([[ 2,  3,  4,  5],
       [ 6, 17, 18,  9],
       [10, 21, 22, 13]])

a
Out[152]: 
array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

a[:,:]+[1,1,1,1]
Out[153]: 
array([[ 2,  3,  4,  5],
       [ 6, 17, 18,  9],
       [10, 21, 22, 13]])

a
Out[154]: 
array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

np.where(a<10,a,10)
Out[155]: 
array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

  a
Out[156]: 
array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

a=np.matrix(np.arange(1,13)).reshape(3,4)

a
Out[158]: 
matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

m.T
Traceback (most recent call last):

  File "<ipython-input-159-a4ee52bc5d60>", line 1, in <module>
    m.T

NameError: name 'm' is not defined




a.T
Out[160]: 
matrix([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

a=np.matrix(np.arange(9)).reshape(3,3)

a
Out[162]: 
matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

a.I
Traceback (most recent call last):

  File "<ipython-input-163-105ed6093821>", line 1, in <module>
    a.I

  File "d:\Users\16476\Anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py", line 836, in getI
    return asmatrix(func(self))

  File "d:\Users\16476\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "d:\Users\16476\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix




import numpy.linalg

numpy.linalg(a)
Traceback (most recent call last):

  File "<ipython-input-165-9601a69546e8>", line 1, in <module>
    numpy.linalg(a)

TypeError: 'module' object is not callable




numpy.linalg.det(a)
Out[166]: 0.0

numpy.linalg.eigvals(a)
Out[167]: array([ 1.33484692e+01, -1.34846923e+00, -1.15433316e-15])

import random

values=[1,2,3,4,5,6]

random.choice(values)
Out[170]: 2

random.choice(values)
Out[171]: 3

random.choice(values)
Out[172]: 3

random.choice(values)
Out[173]: 3

random.choice(values)
Out[174]: 2

random.choice(values)
Out[175]: 5

random.choice(values)
Out[176]: 2

random.choice(values)
Out[177]: 2

random.choice(values)
Out[178]: 5

random.choice(values)
Out[179]: 4

random.choice(values)
Out[180]: 2

random.choice(values)
Out[181]: 4

random.choice(values)
Out[182]: 5

random.choice(values)
Out[183]: 3

random.sample(values,2)
Out[184]: [6, 3]

random.shuffle(values,2)
Traceback (most recent call last):

  File "<ipython-input-185-1a532af8aeaa>", line 1, in <module>
    random.shuffle(values,2)

  File "d:\Users\16476\Anaconda3\lib\random.py", line 283, in shuffle
    j = _int(random() * (i+1))

TypeError: 'int' object is not callable




random.shuffle(values)

values
Out[187]: [5, 2, 6, 3, 1, 4]

random.randint(0,10)
Out[188]: 6

random.random(0,10)
Traceback (most recent call last):

  File "<ipython-input-189-d9ae151f77b7>", line 1, in <module>
    random.random(0,10)

TypeError: random() takes no arguments (2 given)




random.random()
Out[190]: 0.6787107338169545

random.getrandbits(2000)
Out[191]: 65064673577462835504122282079660576594584419506899091788879677305280447902739267176533338223406614483375724583086323647313660147418354706259315053466722062632421622873896693904035890205804801219262045070556715230353206040310919468925808892670344130954534286249297865469608698320589020235321907041253897636683552140955606853337747512195408746365611044743438205068018181825331309490816663684575744825684887342402724444262668653467804513719254077427159866206972908528214615747741613962882593558690462324194350199580522038880600791169505801825575559991989257183402554722439946805894867966082558466684855757

from datetime import timedelta

a=timedelta(days=2,hours=6)

a
Out[194]: datetime.timedelta(days=2, seconds=21600)

b=timedelta(hours=4.5)

c=a+b

c
Out[197]: datetime.timedelta(days=2, seconds=37800)

c.total_seconds()
Out[198]: 210600.0

c.total_seconds()/3600
Out[199]: 58.5

from datetime import datetime

a=datetime(2019,11,26)

print(a+timedelta(day=10))
Traceback (most recent call last):

  File "<ipython-input-202-6ddf1aaad315>", line 1, in <module>
    print(a+timedelta(day=10))

TypeError: 'day' is an invalid keyword argument for __new__()




print(a+timedelta(days=10))
2019-12-06 00:00:00

d=a+timedelta(days=10)

d
Out[205]: datetime.datetime(2019, 12, 6, 0, 0)

d.days
Traceback (most recent call last):

  File "<ipython-input-206-5d3d40811b44>", line 1, in <module>
    d.days

AttributeError: 'datetime.datetime' object has no attribute 'days'




datetime.today()
Out[207]: datetime.datetime(2019, 11, 27, 17, 17, 41, 303856)

from dateutil.relativedelta import relativedelta

a
Out[209]: datetime.datetime(2019, 11, 26, 0, 0)

a+relativedelta(months=+4)
Out[210]: datetime.datetime(2020, 3, 26, 0, 0)

a+relativedelta(months=-4)
Out[211]: datetime.datetime(2019, 7, 26, 0, 0)

b
Out[212]: datetime.timedelta(seconds=16200)

b=datetime(2019,1,22)

d=b-a

d
Out[215]: datetime.timedelta(days=-308)

relativedelta(a,b)
Out[216]: relativedelta(months=+10, days=+4)



def frange(start ,stop,increment):
    x=start
    while x<=stop:
        yield x
        x+=increment
        

frange(1,5,2)
Out[31]: <generator object frange at 0x0000026946AB9CC8>

for i in frange(1,5,2):
    print（ｉ）
  File "<ipython-input-32-422bb8d5ab81>", line 2
    print（ｉ）
           ^
SyntaxError: invalid character in identifier




for i in frange(1,5,2):
    print(i)
    
1
3
5

a=frange(1,5,2)

sum(a)
Out[35]: 9

list(a)
Out[36]: []

print(list(a))
[]

list(frange(0,1,0.125))

Out[38]: [0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1.0]

list(frange(1,5,2))
Out[39]: [1, 3, 5]

a
Out[40]: <generator object frange at 0x00000269469D25C8>

list(a)
Out[41]: []

a==frange(1,5,2)
Out[42]: False

b=frange(1,5,2)

a==b
Out[44]: False

sum(b)
Out[45]: 9

frange(1,5,2)
Out[46]: <generator object frange at 0x00000269469D28C8>

b
Out[47]: <generator object frange at 0x00000269469D2648>

#树节点，深度优先

runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "<ipython-input-49-5fcc9abdec61>", line 1, in <module>
    runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled1.py", line 22, in <module>
    root =Node(0)

TypeError: Node() takes no arguments




runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

class Node:
    def __init__(self,value):
        self._value=value
        self._children=[]
    def __repr__(self):
        return 'Node{(!r)}'.format(self.__value)
    def add_child(self,node):
        self._children.append(node)
    def __inter__(self):
        return iter(self._children)
    def depth_first(self):
        yield self
        for c in self:
            yield from c.depth_first()
if __name__=='__main__':
    root =Node(0)
    child1=Node(1)
    child2=Node(2)
    root.add_child(child1)
    root.add_child(child2)
    child1.add_child(Node(4))
    child1.add_child(Node(5))
    child2.add_child(Node(3))
    child2.add_child(Node(00000))
    

for ch in root.depth_first():
    print(ch)
    
Traceback (most recent call last):

  File "<ipython-input-52-1300f4843ba9>", line 2, in <module>
    print(ch)

  File "<ipython-input-51-ba451f45aebf>", line 6, in __repr__
    return 'Node{(!r)}'.format(self.__value)

AttributeError: 'Node' object has no attribute '_Node__value'




runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "D:\Users\16476\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-54-5fcc9abdec61>", line 1, in <module>
    runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled1.py", line 32
    print(ch)
        ^
IndentationError: expected an indented block




runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')
Traceback (most recent call last):

  File "<ipython-input-55-5fcc9abdec61>", line 1, in <module>
    runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled1.py", line 32, in <module>
    print(ch)

  File "C:/Users/16476/untitled1.py", line 12, in __repr__
    return 'Node{(!r)}'.format(self._value)

ValueError: expected ':' after conversion specifier




class Node:
    def __init__(self,value):
        self._value=value
        self._children=[]
    def __repr__(self):
        return 'Node{(!r)}'.format(self._value)
    def add_child(self,node):
        self._children.append(node)
    def __inter__(self):
        return iter(self._children)
    def depth_first(self):
        yield self
        for c in self:
            yield from c.depth_first()
if __name__=='__main__':
    root =Node(0)
    child1=Node(1)
    child2=Node(2)
    root.add_child(child1)
    root.add_child(child2)
    child1.add_child(Node(4))
    child1.add_child(Node(5))
    child2.add_child(Node(3))
    child2.add_child(Node(00000))
    

for ch in root.depth_first():
        print(ch)
        
Traceback (most recent call last):

  File "<ipython-input-57-bab6c61fe318>", line 2, in <module>
    print(ch)

  File "<ipython-input-56-205a7d19b7ad>", line 6, in __repr__
    return 'Node{(!r)}'.format(self._value)

ValueError: expected ':' after conversion specifier




runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')
Node(0)
Traceback (most recent call last):

  File "<ipython-input-58-5fcc9abdec61>", line 1, in <module>
    runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "D:\Users\16476\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/16476/untitled1.py", line 31, in <module>
    for ch in root.depth_first():

  File "C:/Users/16476/untitled1.py", line 19, in depth_first
    for c in self:

TypeError: 'Node' object is not iterable




runfile('C:/Users/16476/untitled1.py', wdir='C:/Users/16476')
Node(0)
Node(1)
Node(4)
Node(5)
Node(2)
Node(3)
Node(0)

class Node:
    def __init__(self,value):
        self._value=value
        self._children=[]
    def __repr__(self):
        return 'Node({!r})'.format(self._value)
    def add_child(self,node):
        self._children.append(node)
    def __iter__(self):
        return iter(self._children)
    def depth_first(self):
        yield self
        for c in self:
            yield from c.depth_first()
if __name__=='__main__':
    root =Node(0)
    child1=Node(1)
    child2=Node(2)
    root.add_child(child1)
    root.add_child(child2)
    child1.add_child(Node(4))
    child1.add_child(Node(5))
    child2.add_child(Node(3))
    child2.add_child(Node(00000))
    for ch in root.depth_first():
        print(ch)
        
Node(0)
Node(1)
Node(4)
Node(5)
Node(2)
Node(3)
Node(0)

next(root)
Traceback (most recent call last):

  File "<ipython-input-61-49ee399c1ae1>", line 1, in <module>
    next(root)

TypeError: 'Node' object is not an iterator




next(root.depth_first())
Out[62]: Node(0)

next(root.depth_first())
Out[63]: Node(0)

next(iter(root))
Out[64]: Node(1)

next(iter(root))
Out[65]: Node(1)



next(iter(root))
Out[66]: Node(1)

root
Out[67]: Node(0)

for ch in root:
    print(ch)
    
Node(1)
Node(2)

a=[1,2,3,4]

for x in reversed( a):
    print(a)
    
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]

for x in reversed( a):
    print(x)
    
4
3
2
1

f=open(ck.txt)
Traceback (most recent call last):

  File "<ipython-input-72-df7120787cfa>", line 1, in <module>
    f=open(ck.txt)

NameError: name 'ck' is not defined




f=open('ck.txt')
Traceback (most recent call last):

  File "<ipython-input-73-c38b2b982978>", line 1, in <module>
    f=open('ck.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'ck.txt'




f=open('ck.txt')

for line in reversed(list(f)):
    print (line)
    
'''

Out[7]: Counter({1: 3, 2: 2, 3: 1})

wc



wc.update()



Out[5]: [(1, 3), (2, 2)]

a



a=wc.most_common(2)



wc=Counter(w)



from collections import Counter

'''

w=[1,1,1,2,2,3]

a[s]

s=slice(2,4)

list(dedupe(a))

a=np.random.randint(10,size=10)

            seen.add(item)

            yield item 

        if item not in seen:

    for item in items:

    seen = set()

def dedupe(items):

import numpy as np

"""

@author: 16476



Created on Sun Nov 17 11:16:49 2019

"""

# -*- coding: utf-8 -*-


runfile('C:/Users/16476/untitled1.py')

for line in Countdown(f):
    print (line)
    
Traceback (most recent call last):

  File "<ipython-input-77-8f5d9ab26165>", line 1, in <module>
    for line in Countdown(f):

  File "C:/Users/16476/untitled1.py", line 6, in __iter__
    while n>0:

TypeError: '>' not supported between instances of '_io.TextIOWrapper' and 'int'




for line in Countdown(f).__reversed__:
    print (line)
    
Traceback (most recent call last):

  File "<ipython-input-78-a68512b546e3>", line 1, in <module>
    for line in Countdown(f).__reversed__:

TypeError: 'method' object is not iterable




a=Countdown(f)

a
Out[80]: <__main__.Countdown at 0x26946a74a88>

a.start
Out[81]: <_io.TextIOWrapper name='ck.txt' mode='r' encoding='cp936'>

reversed(a)
Out[82]: <generator object Countdown.__reversed__ at 0x0000026946A76F48>

for line in reversed(a):
    print (line)
    
Traceback (most recent call last):

  File "<ipython-input-83-f7f5b705532b>", line 1, in <module>
    for line in reversed(a):

  File "C:/Users/16476/untitled1.py", line 11, in __reversed__
    while n<=self.start:

TypeError: '<=' not supported between instances of 'int' and '_io.TextIOWrapper'



